audit select table,insert table, update table, delete table by GFP_SPACEMAN,GTS_USER_RO,TBA_OBDOCK_USER,AFT_OFP_USER,AFT_SORTATION,SHERLOCK_USER,AFT_BATSUSER,AFT_RODEOUSER,AFT_P2USER,AFT_RECEIVEUSER,AFT_SHIPUSER,AFT_PICKSCHED_USER,AFT_WD_USER,AFT_SHRINQ_USER,GFP_RETEXAPPS,AFT_STOWUSER,AFT_PACKUSER,AFT_BOXUSER,GFP_SKUMAS,GFP_REMOVALS,AFT_PICKUSER,TBA_OBTSHIP_USER,AFT_INBOUNDDOCK_USER by access;

noaudit select table,insert table, update table, delete table by GFP_SPACEMAN,GTS_USER_RO,TBA_OBDOCK_USER,AFT_OFP_USER,AFT_SORTATION,SHERLOCK_USER,AFT_BATSUSER,AFT_RODEOUSER,AFT_P2USER,AFT_RECEIVEUSER,AFT_SHIPUSER,AFT_PICKSCHED_USER,AFT_WD_USER,AFT_SHRINQ_USER,GFP_RETEXAPPS,AFT_STOWUSER,AFT_PACKUSER,AFT_BOXUSER,GFP_SKUMAS,GFP_REMOVALS,AFT_PICKUSER,TBA_OBTSHIP_USER;
--
audit all by AFT_ACWUSER,AFT_ATROPS_USER,AFT_BATSUSER,AFT_BOXUSER,AFT_CAPOUSER,AFT_CROSSDOCK_USER,AFT_DBA_DOSQL_USER,AFT_FCDASHUSER,AFT_FCIT_USER,AFT_FCPORTAL,AFT_FLOWC_USER,AFT_IA_USER,AFT_IDQUSER,AFT_IPCUSER,AFT_MFG_USER,AFT_NT4SUSER,AFT_OFP_USER,AFT_P2USER,AFT_PACKUSER,AFT_PICKSCHED_USER,AFT_PICKUSER,AFT_PICKUSER_ADG,AFT_PICTUSER,AFT_PRDCOMP_USER,AFT_PREP_USER,AFT_RECEIVEUSER,AFT_RODEOUSER,AFT_RSIDEV_USER,AFT_SCOPE_USER,AFT_SDETOOLS,AFT_SHAREDUSER,AFT_SHIPUSER,AFT_SHRINQ_USER,AFT_SORTATION,AFT_SOX_COLLECTOR,AFT_STOWUSER,AFT_VIRT_USER,AFT_WDFCTOOLS_USER,AFT_WD_USER,AFT_WISHUSER,CCA_USER_RW,CRETURNS_USER,FEX_USER,FEX_USER_ADG,GFP_GREENAPPS,GFP_ICQAUSER,GFP_LABORMAN,GFP_MAESTRO,GFP_OIHUSER,GFP_REMOVALS,GFP_RETEXAPPS,GFP_REVOREPORTS,GFP_RMRC_USER,GFP_SKUMAS,GFP_SPACEMAN,GPS_AFT_SERVICE,GTS_USER_RO,SHERLOCK_USER,TBA_OBDOCK_USER,TBA_OBTSHIP_USER,WD_SMARTALARMS_USER by access;

noaudit all by AFT_ACWUSER,AFT_ATROPS_USER,AFT_BATSUSER,AFT_BOXUSER,AFT_CAPOUSER,AFT_CROSSDOCK_USER,AFT_DBA_DOSQL_USER,AFT_FCDASHUSER,AFT_FCIT_USER,AFT_FCPORTAL,AFT_FLOWC_USER,AFT_IA_USER,AFT_IDQUSER,AFT_IPCUSER,AFT_MFG_USER,AFT_NT4SUSER,AFT_OFP_USER,AFT_P2USER,AFT_PACKUSER,AFT_PICKSCHED_USER,AFT_PICKUSER,AFT_PICKUSER_ADG,AFT_PICTUSER,AFT_PRDCOMP_USER,AFT_PREP_USER,AFT_RECEIVEUSER,AFT_RODEOUSER,AFT_RSIDEV_USER,AFT_SCOPE_USER,AFT_SDETOOLS,AFT_SHAREDUSER,AFT_SHIPUSER,AFT_SHRINQ_USER,AFT_SORTATION,AFT_SOX_COLLECTOR,AFT_STOWUSER,AFT_VIRT_USER,AFT_WDFCTOOLS_USER,AFT_WD_USER,AFT_WISHUSER,CCA_USER_RW,CRETURNS_USER,FEX_USER,FEX_USER_ADG,GFP_GREENAPPS,GFP_ICQAUSER,GFP_LABORMAN,GFP_MAESTRO,GFP_OIHUSER,GFP_REMOVALS,GFP_RETEXAPPS,GFP_REVOREPORTS,GFP_RMRC_USER,GFP_SKUMAS,GFP_SPACEMAN,GPS_AFT_SERVICE,GTS_USER_RO,SHERLOCK_USER,TBA_OBDOCK_USER,TBA_OBTSHIP_USER,WD_SMARTALARMS_USER;



-- query...

select distinct USERNAME,USERHOST,ACTION,OBJ_NAME from DBA_AUDIT_TRAIL where OBJ_NAME in ('CONTAINER_TYPES','INVENTORY_BINDINGS','CONTAINER_PROCESSED_REQUESTS','COST_PARTITIONS','COST_PROPERTIES','INVENTORY_AVAILABILITY_CHANGES','INVENTORY_COST_ITEMS','INVENTORY_COST_MESSAGES','INVENTORY_COST_TXN_AUDITS','ITEM_PROCESSED_REQUESTS','INVENTORY_COSTS','CONTAINER_MOVE_SEGMENTS','CONTAINER_CONTAINMENT_MAPS','CONTAINERS_PHYSICAL','BINEDIT_ENTRIES','INV_LEVEL_BY_OWNER_PHYSICAL','INVENTORY_ADJUSTMENT_BY_OWNER','SIDELINE_REQUESTS','INV_LVL_PUBLISHED_FCSKUS','INV_COST_MESSAGE_DATAGRAMS','INV_LVL_SWEEPER_PROPERTIES','COST_MESSAGES','INVENTORY_COST_REQUESTS','COST_PLACEHOLDERS','INVENTORY_OWNER_GRP_LOCATIONS','BIN_ITEMS','CONSUMED_INVENTORY_COSTS','CONTAINER_NOTIFICATIONS','HIST_INVENTORY_COST_ITEMS','INV_LEVEL_BY_LOCATION_PHYSICAL','INVENTORY_ADJUSTMENT_ITEMS','INVENTORY_BINDING_ITEMS','INVENTORY_CONSUMER_TYPES','INVENTORY_COST_MESSAGE_IOGS','INVENTORY_FNSKU_PARTITIONS','INVENTORY_NOTIFICATIONS','FC_PROPERTY_VALUES','CCSP_MONETARY_DETAILS','COMPLETED_CUST_SHIPMENT_PKGS','COMPLETED_CUSTOMER_SHIPMENTS','CUSTOMER_SHIPMENT_ITEMS','FC_FULFILLMENT_DOCUMENTS','FC_FULFILLMENT_REQUEST_ITEMS','FC_PROCESS_EXCEPTIONS','FULFILLMENT_SHIPMENT_ITEM_MAP','FULFILLMENT_SHIPMENT_MAP','ORDER_PIPELINE_EVENTS','PENDING_CUSTOMER_SHIPMENTS','PENDING_SHIPMENT_ITEMS','REJECTED_FULFILLMENT_REQS','SHIP_REQUEST_ITEMS','SHIPMENT_ITEM_PROPERTY_VALUES','SHIPMENT_PROPERTY_VALUES','SHIPMENT_REQUESTS','SHIPMENT_REVISION','FC_WF_PCS_CHANGES','FC_WF_PCS_CHANGE_DETAILS','TRANSFER_REQUESTS','TRANSFER_REQUEST_ITEMS','TRANSFER_REQUEST_ITEM_BINDINGS','TRANSFER_REQUEST_UPDATES','PCSP_MONETARY_DETAILS','PENDING_CUST_SHIPMENT_PKGS') and TIMESTAMP > sysdate - 1/24 order by 4;


select distinct a.USERNAME,a.USERHOST,a.OBJ_NAME,b.NAME from DBA_AUDIT_TRAIL a,AUDIT_ACTIONS b where a.OBJ_NAME in ('CONTAINER_TYPES','INVENTORY_BINDINGS','CONTAINER_PROCESSED_REQUESTS','COST_PARTITIONS','COST_PROPERTIES','INVENTORY_AVAILABILITY_CHANGES','INVENTORY_COST_ITEMS','INVENTORY_COST_MESSAGES','INVENTORY_COST_TXN_AUDITS','ITEM_PROCESSED_REQUESTS','INVENTORY_COSTS','CONTAINER_MOVE_SEGMENTS','CONTAINER_CONTAINMENT_MAPS','CONTAINERS_PHYSICAL','BINEDIT_ENTRIES','INV_LEVEL_BY_OWNER_PHYSICAL','INVENTORY_ADJUSTMENT_BY_OWNER','SIDELINE_REQUESTS','INV_LVL_PUBLISHED_FCSKUS','INV_COST_MESSAGE_DATAGRAMS','INV_LVL_SWEEPER_PROPERTIES','COST_MESSAGES','INVENTORY_COST_REQUESTS','COST_PLACEHOLDERS','INVENTORY_OWNER_GRP_LOCATIONS','BIN_ITEMS','CONSUMED_INVENTORY_COSTS','CONTAINER_NOTIFICATIONS','HIST_INVENTORY_COST_ITEMS','INV_LEVEL_BY_LOCATION_PHYSICAL','INVENTORY_ADJUSTMENT_ITEMS','INVENTORY_BINDING_ITEMS','INVENTORY_CONSUMER_TYPES','INVENTORY_COST_MESSAGE_IOGS','INVENTORY_FNSKU_PARTITIONS','INVENTORY_NOTIFICATIONS','FC_PROPERTY_VALUES','CCSP_MONETARY_DETAILS','COMPLETED_CUST_SHIPMENT_PKGS','COMPLETED_CUSTOMER_SHIPMENTS','CUSTOMER_SHIPMENT_ITEMS','FC_FULFILLMENT_DOCUMENTS','FC_FULFILLMENT_REQUEST_ITEMS','FC_PROCESS_EXCEPTIONS','FULFILLMENT_SHIPMENT_ITEM_MAP','FULFILLMENT_SHIPMENT_MAP','ORDER_PIPELINE_EVENTS','PENDING_CUSTOMER_SHIPMENTS','PENDING_SHIPMENT_ITEMS','REJECTED_FULFILLMENT_REQS','SHIP_REQUEST_ITEMS','SHIPMENT_ITEM_PROPERTY_VALUES','SHIPMENT_PROPERTY_VALUES','SHIPMENT_REQUESTS','SHIPMENT_REVISION','FC_WF_PCS_CHANGES','FC_WF_PCS_CHANGE_DETAILS','TRANSFER_REQUESTS','TRANSFER_REQUEST_ITEMS','TRANSFER_REQUEST_ITEM_BINDINGS','TRANSFER_REQUEST_UPDATES','PCSP_MONETARY_DETAILS','PENDING_CUST_SHIPMENT_PKGS') and a.TIMESTAMP > sysdate - 1/24 and a.action=b.action order by 3;


--
select listagg(DATABASE_USERNAME,', ') within group(order by DATABASE_USERNAME) from (select distinct DATABASE_USERNAME from admin.SPDA_CRED_MGR_ACTIONS where DATABASE_USERNAME in (select distinct username from dba_users));

--
audit all on booker.containers by access;
audit all on containers by access;
audit all on booker.COMPLETE_BI_INVODS by access;
audit all on COMPLETE_BI_INVODS by access;
audit all on booker.COMPLETE_IC_DCLEX1_INVODS by access;
audit all on COMPLETE_IC_DCLEX1_INVODS by access;
audit all on booker.COMPLETE_ILBL_INVODS by access;
audit all on COMPLETE_ILBL_INVODS by access;
audit all on booker.COMPLETE_ILBO_INVODS by access;
audit all on COMPLETE_ILBO_INVODS by access;
audit all on booker.COMPLETE_PCS_INVODS by access;
audit all on COMPLETE_PCS_INVODS by access;
audit all on booker.INVENTORY_LEVEL_BY_LOCATION by access;
audit all on INVENTORY_LEVEL_BY_LOCATION by access;
audit all on booker.INVENTORY_LEVEL_BY_OWNER by access;
audit all on INVENTORY_LEVEL_BY_OWNER by access;
audit all on booker.INVENTORY_LVL_BY_OWNER_REPLEN by access;
audit all on INVENTORY_LVL_BY_OWNER_REPLEN by access;
audit all on booker.INV_LEVEL_BY_OWNER_FIFO by access;
audit all on INV_LEVEL_BY_OWNER_FIFO by access;
audit all on booker.INV_LVL_BY_LOCATION_REPLEN by access;
audit all on INV_LVL_BY_LOCATION_REPLEN by access;
audit all on booker.SRW_INVENTORY_LEVEL_LOCATION by access;
audit all on SRW_INVENTORY_LEVEL_LOCATION by access;
audit all on booker.UNASSIGNED_INVENTORY by access;
audit all on UNASSIGNED_INVENTORY by access;

--
select distinct a.USERNAME,a.USERHOST,a.OBJ_NAME,b.NAME from DBA_AUDIT_TRAIL a,AUDIT_ACTIONS b where a.OBJ_NAME in ('CONTAINERS','COMPLETE_BI_INVODS','COMPLETE_IC_DCLEX1_INVODS','COMPLETE_ILBL_INVODS','COMPLETE_ILBO_INVODS','COMPLETE_PCS_INVODS','INVENTORY_LEVEL_BY_LOCATION','INVENTORY_LEVEL_BY_OWNER','INVENTORY_LVL_BY_OWNER_REPLEN','INV_LEVEL_BY_OWNER_FIFO','INV_LVL_BY_LOCATION_REPLEN','INV_LVL_BY_LOCATION_REPLEN','SRW_INVENTORY_LEVEL_LOCATION','UNASSIGNED_INVENTORY') and a.TIMESTAMP > sysdate - 1/24 order by 4;


--

drop public synonym COMPLETE_BI_INVODS;
drop public synonym COMPLETE_IC_DCLEX1_INVODS;
drop public synonym COMPLETE_ILBL_INVODS;
drop public synonym COMPLETE_ILBO_INVODS;
drop public synonym INVENTORY_LVL_BY_OWNER_REPLEN;
drop public synonym INV_LEVEL_BY_OWNER_FIFO;
drop public synonym INV_LVL_BY_LOCATION_REPLEN;
drop public synonym UNASSIGNED_INVENTORY;
drop public synonym COMPLETE_PCS_INVODS;
drop public synonym SRW_INVENTORY_LEVEL_LOCATION;

