CREATE USER "DMS_USER_SORT" IDENTIFIED BY VALUES 'S:434B0B0B87BB8280A254A5E0370E8D8E303A2E0FA35E3810173FBE93659F;B89B84D2F5EEC62F' TEMPORARY TABLESPACE "TEMP" PROFILE "APP_LOGIN_ATTEMPT_PROFILE";
alter user DMS_USER_SORT identified by P#Dms1Use;
GRANT DBA to DMS_USER_SORT;
GRANT ALTER ANY TABLE TO DMS_USER_SORT;
GRANT ALTER DATABASE TO DMS_USER_SORT;
GRANT UNLIMITED TABLESPACE TO DMS_USER_SORT;
GRANT SELECT ANY TABLE TO DMS_USER_SORT;
GRANT SELECT ANY TRANSACTION TO DMS_USER_SORT;
GRANT CREATE SESSION TO DMS_USER_SORT;
GRANT SELECT ON SYS.V_$LOGMNR_CONTENTS TO DMS_USER_SORT;
GRANT SELECT ON SYS.V_$LOGMNR_LOGS TO DMS_USER_SORT;
GRANT SELECT ON SYS.V_$TIMEZONE_NAMES TO DMS_USER_SORT;
GRANT SELECT ON SYS.ALL_CATALOG TO DMS_USER_SORT;
GRANT SELECT ON SYS.ALL_INDEXES TO DMS_USER_SORT;
GRANT SELECT ON SYS.ALL_IND_COLUMNS TO DMS_USER_SORT;
GRANT SELECT ON SYS.ALL_OBJECTS TO DMS_USER_SORT;
GRANT SELECT ON SYS.DBA_OBJECTS TO DMS_USER_SORT;
GRANT SELECT ON SYS.ALL_TABLES TO DMS_USER_SORT;
GRANT SELECT ON SYS.ALL_TAB_COLS TO DMS_USER_SORT;
GRANT SELECT ON SYS.ALL_USERS TO DMS_USER_SORT;
GRANT SELECT ON SYS.ALL_VIEWS TO DMS_USER_SORT;
GRANT SELECT ON SYS.ALL_CONSTRAINTS TO DMS_USER_SORT;
GRANT SELECT ON SYS.ALL_LOG_GROUPS TO DMS_USER_SORT;
GRANT SELECT ON SYS.ALL_CONS_COLUMNS TO DMS_USER_SORT;
GRANT SELECT ON SYS.ALL_TAB_PARTITIONS TO DMS_USER_SORT;
GRANT SELECT ON SYS.DBA_TABLESPACES TO DMS_USER_SORT;
GRANT SELECT ON SYS.ALL_ENCRYPTED_COLUMNS TO DMS_USER_SORT;
GRANT SELECT ON SYS.OBJ$ TO DMS_USER_SORT;
GRANT SELECT ON SYS.V_$ARCHIVED_LOG TO DMS_USER_SORT;
GRANT SELECT ON SYS.V_$DATABASE TO DMS_USER_SORT;
GRANT SELECT ON SYS.V_$NLS_PARAMETERS TO DMS_USER_SORT;
GRANT SELECT ON SYS.V_$PARAMETER TO DMS_USER_SORT;
GRANT SELECT ON SYS.V_$LOGFILE TO DMS_USER_SORT;
GRANT SELECT ON SYS.V_$TRANSACTION TO DMS_USER_SORT;
GRANT SELECT ON SYS.V_$THREAD TO DMS_USER_SORT;
GRANT SELECT ON SYS.DBA_REGISTRY TO DMS_USER_SORT;
GRANT SELECT ON SYS.V_$LOG TO DMS_USER_SORT;
GRANT EXECUTE ON SYS.DBMS_LOGMNR TO DMS_USER_SORT;
GRANT EXECUTE ON SYS.DBMS_CRYPTO TO DMS_USER_SORT;

CREATE OR REPLACE TRIGGER SYS.DMS_USER_SORT_TRG
AFTER LOGON
ON database when (user='DMS_USER_SORT')
DECLARE
stmt VARCHAR2(200);
BEGIN
stmt := 'alter session set optimizer_mode=first_rows';
execute immediate stmt;
END;
/


