SELECT
 FILE#, PHYRDS, PHYWRTS, PHYBLKRD, PHYBLKWRT, SINGLEBLKRDS,
 READTIM, WRITETIM, SINGLEBLKRDTIM, AVGIOTIM, LSTIOTIM,
 MINIOTIM, MAXIORTM, MAXIOWTM
 FROM
 V$FILESTAT
 WHERE
 FILE# = &file_id;