ALTER SESSION enable parallel query;
ALTER SESSION force parallel query;

select /*+ parallel(a,16) */ max(CREATION_DATE), max(LAST_UPDATED_DATE) TRANSFER_MANIFESTS from booker.TRANSFER_MANIFESTS a;
select /*+ parallel(a,16) */ max(CREATION_DATE), max(LAST_UPDATED_DATE) TRANSFER_MANIFEST_ITEMS from booker.TRANSFER_MANIFEST_ITEMS a;
select /*+ parallel(a,16) */ max(CREATION_DATE), max(LAST_UPDATED_DATE) TRANSFER_OUTBD_CONTAINERS from booker.TRANSFER_OUTBD_CONTAINERS a;
select /*+ parallel(a,16) */ max(CREATION_DATE), max(LAST_UPDATED_DATE) TRANSFER_OUTBD_CONTAINER_ITEMS from booker.TRANSFER_OUTBD_CONTAINER_ITEMS a;
select /*+ parallel(a,16) */ max(CREATION_DATE), max(LAST_UPDATED_DATE) TRANSFER_ITEM_FINANCE_SUPPL from booker.TRANSFER_ITEM_FINANCE_SUPPL a;
select /*+ parallel(a,16) */ max(CREATION_DATE), max(LAST_UPDATED_DATE) TRANSFER_DELIVERIES from booker.TRANSFER_DELIVERIES a;
select /*+ parallel(a,16) */ max(CREATION_DATE), max(LAST_UPDATED_DATE) TRANSFER_DELIVERY_ITEMS from booker.TRANSFER_DELIVERY_ITEMS a;
select /*+ parallel(a,16) */ max(CREATION_DATE), max(LAST_UPDATED_DATE) TRANSFER_INBD_CONTAINERS from booker.TRANSFER_INBD_CONTAINERS a;
select /*+ parallel(a,16) */ max(CREATION_DATE), max(LAST_UPDATED_DATE) TRANSFER_INBD_CONTAINER_ITEMS from booker.TRANSFER_INBD_CONTAINER_ITEMS a;
select /*+ parallel(a,16) */ max(CREATION_DATE), max(LAST_UPDATED_DATE) TRANSFER_RECEIVE_ACTIONS from booker.TRANSFER_RECEIVE_ACTIONS a;
