ALTER SESSION enable PARALLEL query;
ALTER SESSION force PARALLEL query;

select /*+ FULL(a) PARALLEL(a,8) */ count(1) TRANSFER_MANIFESTS from booker.TRANSFER_MANIFESTS a;
select /*+ FULL(a) PARALLEL(a,8) */ count(1) TRANSFER_MANIFEST_ITEMS from booker.TRANSFER_MANIFEST_ITEMS a;
select /*+ FULL(a) PARALLEL(a,8) */ count(1) TRANSFER_OUTBD_CONTAINERS from booker.TRANSFER_OUTBD_CONTAINERS a;
select /*+ FULL(a) PARALLEL(a,8) */ count(1) TRANSFER_OUTBD_CONTAINER_ITEMS from booker.TRANSFER_OUTBD_CONTAINER_ITEMS a;
select /*+ FULL(a) PARALLEL(a,8) */ count(1) TRANSFER_ITEM_FINANCE_SUPPL from booker.TRANSFER_ITEM_FINANCE_SUPPL a;
select /*+ FULL(a) PARALLEL(a,8) */ count(1) DMS_EDIT_REQUESTS from booker.DMS_EDIT_REQUESTS a;
