select count(1) TRANSFER_MANIFESTS from booker.TRANSFER_MANIFESTS a;
select  count(1) TRANSFER_MANIFEST_ITEMS from booker.TRANSFER_MANIFEST_ITEMS a;
select count(1) TRANSFER_OUTBD_CONTAINERS from booker.TRANSFER_OUTBD_CONTAINERS a;
select count(1) TRANSFER_OUTBD_CONTAINER_ITEMS from booker.TRANSFER_OUTBD_CONTAINER_ITEMS a;
select  count(1) TRANSFER_ITEM_FINANCE_SUPPL from booker.TRANSFER_ITEM_FINANCE_SUPPL a;
select  count(1) DMS_EDIT_REQUESTS from booker.DMS_EDIT_REQUESTS a;

select  count(1) TRANSFER_DELIVERIES from booker.TRANSFER_DELIVERIES a;
select  count(1) TRANSFER_DELIVERY_ITEMS from booker.TRANSFER_DELIVERY_ITEMS a;
select  count(1) TDI_ICI_IDS from booker.TDI_ICI_IDS a;
select count(1) TRANSFER_INBD_CONTAINERS from booker.TRANSFER_INBD_CONTAINERS a;
select count(1) TRANSFER_INBD_CONTAINER_ITEMS from booker.TRANSFER_INBD_CONTAINER_ITEMS a;
select  count(1) TRANSFER_RECEIVE_ACTIONS from booker.TRANSFER_RECEIVE_ACTIONS a;
