select * from DBA_LOG_GROUPS;
 ALTER DATABASE ADD SUPPLEMENTAL LOG DATA;
 alter table booker.data_proc_resource_versions ADD SUPPLEMENTAL LOG DATA (PRIMARY KEY) COLUMNS;
 alter table booker.work_areas ADD SUPPLEMENTAL LOG DATA (PRIMARY KEY) COLUMNS;
 alter table booker.lh_function_time_aggs_daily ADD SUPPLEMENTAL LOG DATA (PRIMARY KEY) COLUMNS;
 alter table booker.lh_function_time_aggs_monthly ADD SUPPLEMENTAL LOG DATA (PRIMARY KEY) COLUMNS;
 alter table booker.lh_function_time_aggs_intraday ADD SUPPLEMENTAL LOG DATA (PRIMARY KEY) COLUMNS;
 alter table booker.lh_unit_aggs_weekly ADD SUPPLEMENTAL LOG DATA (PRIMARY KEY) COLUMNS;
 alter table booker.partition_last_updated_dates ADD SUPPLEMENTAL LOG DATA (PRIMARY KEY) COLUMNS;
 alter table booker.break_shifts ADD SUPPLEMENTAL LOG DATA (PRIMARY KEY) COLUMNS;
 alter table booker.labor_transfer_assign_hist ADD SUPPLEMENTAL LOG DATA (PRIMARY KEY) COLUMNS;
 alter table booker.labor_transfer_assignments ADD SUPPLEMENTAL LOG DATA (PRIMARY KEY) COLUMNS;
 alter table booker.labor_transfer_events ADD SUPPLEMENTAL LOG DATA (PRIMARY KEY) COLUMNS;
 alter table booker.manual_func_time_assgn_history ADD SUPPLEMENTAL LOG DATA (PRIMARY KEY) COLUMNS;
 alter table booker.manual_function_time_assgnmnts ADD SUPPLEMENTAL LOG DATA (PRIMARY KEY) COLUMNS;
 alter table booker.lh_unit_aggs_daily ADD SUPPLEMENTAL LOG DATA (PRIMARY KEY) COLUMNS;
 alter table booker.lh_unit_aggs_intraday ADD SUPPLEMENTAL LOG DATA (PRIMARY KEY) COLUMNS;
 alter table booker.lh_unit_aggs_monthly ADD SUPPLEMENTAL LOG DATA (PRIMARY KEY) COLUMNS;
 alter table booker.lh_asin_unit_aggs ADD SUPPLEMENTAL LOG DATA (PRIMARY KEY) COLUMNS;
 alter table booker.warehouses ADD SUPPLEMENTAL LOG DATA (PRIMARY KEY) COLUMNS;
 alter table booker.break_instances ADD SUPPLEMENTAL LOG DATA (PRIMARY KEY) COLUMNS;
 alter table booker.employee_target_uph ADD SUPPLEMENTAL LOG DATA (PRIMARY KEY) COLUMNS;
 alter table booker.last_archive_run_time ADD SUPPLEMENTAL LOG DATA (PRIMARY KEY) COLUMNS;
 alter table booker.lh_job_sessions ADD SUPPLEMENTAL LOG DATA (PRIMARY KEY) COLUMNS;
 alter table booker.work_area_process_functions ADD SUPPLEMENTAL LOG DATA (PRIMARY KEY) COLUMNS;
 alter table booker.break_schedules ADD SUPPLEMENTAL LOG DATA (PRIMARY KEY) COLUMNS;
 alter table booker.break_service_audit_log ADD SUPPLEMENTAL LOG DATA (PRIMARY KEY) COLUMNS;
 alter table booker.daily_employee_labor_hours ADD SUPPLEMENTAL LOG DATA (PRIMARY KEY) COLUMNS;
 alter table booker.line_item_daily_plan_values ADD SUPPLEMENTAL LOG DATA (PRIMARY KEY) COLUMNS;
 alter table booker.data_proc_resource_timestamps ADD SUPPLEMENTAL LOG DATA (PRIMARY KEY) COLUMNS;
 alter table booker.default_work_areas ADD SUPPLEMENTAL LOG DATA (PRIMARY KEY) COLUMNS;
 alter table booker.time_clock_punch_events ADD SUPPLEMENTAL LOG DATA (PRIMARY KEY) COLUMNS;
 alter table booker.job_session_messages ADD SUPPLEMENTAL LOG DATA (PRIMARY KEY) COLUMNS;
 alter table booker.lh_function_time_aggs_weekly ADD SUPPLEMENTAL LOG DATA (PRIMARY KEY) COLUMNS;
 alter table booker.lh_function_time_segments ADD SUPPLEMENTAL LOG DATA (PRIMARY KEY) COLUMNS;
 alter table booker.unit_messages ADD SUPPLEMENTAL LOG DATA (PRIMARY KEY) COLUMNS;
 alter table booker.restricted_org_emp_mappings ADD SUPPLEMENTAL LOG DATA (PRIMARY KEY) COLUMNS;
 alter table booker.ppr_lineitem_daily_overrides ADD SUPPLEMENTAL LOG DATA (PRIMARY KEY) COLUMNS;
 alter table booker.ppr_report_aggs ADD SUPPLEMENTAL LOG DATA (PRIMARY KEY) COLUMNS;
 alter table booker.ppr_report_lineitem_aggs ADD SUPPLEMENTAL LOG DATA (PRIMARY KEY) COLUMNS;
 alter table booker.data_proc_resource_ver_deps ADD SUPPLEMENTAL LOG DATA (PRIMARY KEY) COLUMNS;
 alter table booker.break_shift_intervals ADD SUPPLEMENTAL LOG DATA (PRIMARY KEY) COLUMNS;
 alter table booker.clock_punch_messages ADD SUPPLEMENTAL LOG DATA (PRIMARY KEY) COLUMNS;
 alter table booker.cum_func_time_aggs ADD SUPPLEMENTAL LOG DATA (PRIMARY KEY) COLUMNS;

alter table booker.data_proc_resource_versions ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
 alter table booker.work_areas ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
 alter table booker.lh_function_time_aggs_daily ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
 alter table booker.lh_function_time_aggs_monthly ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
 alter table booker.lh_function_time_aggs_intraday ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
 alter table booker.lh_unit_aggs_weekly ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
 alter table booker.partition_last_updated_dates ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
 alter table booker.break_shifts ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
 alter table booker.labor_transfer_assign_hist ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
 alter table booker.labor_transfer_assignments ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
 alter table booker.labor_transfer_events ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
 alter table booker.manual_func_time_assgn_history ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
 alter table booker.manual_function_time_assgnmnts ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
 alter table booker.lh_unit_aggs_daily ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
 alter table booker.lh_unit_aggs_intraday ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
 alter table booker.lh_unit_aggs_monthly ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
 alter table booker.lh_asin_unit_aggs ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
 alter table booker.warehouses ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
 alter table booker.break_instances ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
 alter table booker.employee_target_uph ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
 alter table booker.last_archive_run_time ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
 alter table booker.lh_job_sessions ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
 alter table booker.work_area_process_functions ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
 alter table booker.break_schedules ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
 alter table booker.break_service_audit_log ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
 alter table booker.daily_employee_labor_hours ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
 alter table booker.line_item_daily_plan_values ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
 alter table booker.data_proc_resource_timestamps ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
 alter table booker.default_work_areas ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
 alter table booker.time_clock_punch_events ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
 alter table booker.job_session_messages ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
 alter table booker.lh_function_time_aggs_weekly ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
 alter table booker.lh_function_time_segments ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
 alter table booker.unit_messages ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
 alter table booker.restricted_org_emp_mappings ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
 alter table booker.ppr_lineitem_daily_overrides ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
 alter table booker.ppr_report_aggs ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
 alter table booker.ppr_report_lineitem_aggs ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
 alter table booker.data_proc_resource_ver_deps ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
 alter table booker.break_shift_intervals ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
 alter table booker.clock_punch_messages ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
 alter table booker.cum_func_time_aggs ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;

 select * from DBA_LOG_GROUPS;
