CREATE MATERIALIZED VIEW "BOOKER"."EXPORT_SIGNATURE_IMAGES_EU" ("EXPORT_SIGNATURE_ID", "IMAGE_USAGE_ID", "IMAGE_FORMAT_ID", "IMAGE_DATA", "CREATED_BY", "CREATION_DATE", "LAST_UPDATED_BY", "LAST_UPDATED_DATE")
  ORGANIZATION HEAP PCTFREE 5 PCTUSED 40 INITRANS 2 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DOMAIN"
 LOB ("IMAGE_DATA") STORE AS BASICFILE (
  TABLESPACE "DOMAIN" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT))
  BUILD IMMEDIATE
  USING INDEX PCTFREE 5 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DOMAIN_IDX"
  REFRESH FAST ON DEMAND START WITH sysdate+0 NEXT SYSDATE+(30/(24*60))
  WITH PRIMARY KEY USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE QUERY REWRITE
 AS (	 SELECT  EXPORT_SIGNATURE_ID
,IMAGE_USAGE_ID
,IMAGE_FORMAT_ID
,IMAGE_DATA
,CREATED_BY
,CREATION_DATE
,LAST_UPDATED_BY
,LAST_UPDATED_DATE
FROM
"BOOKER"."EXPORT_SIGNATURE_IMAGES_EU"@"FCHQ1EU.AMAZON"
);
