set numwidth 25
column SQL_ID for a15
column SQL_TEXT_TO_SQL_ID for a20
select 
sys.DBMS_SQLTUNE_UTIL0.SQLTEXT_TO_SIGNATURE(SQL_TEXT) SQL_TEXT_to_SIGNATURE,
SIGNATURE,
to_char(SIGNATURE,'fmXXXXXXXXXXXXXXXXX') hex_SIGNATURE,
'SQL_'||lower(to_char(SIGNATURE,'fmXXXXXXXXXXXXXXXXX')) SIGNATURE_to_SQL_HANDLE,
SQL_HANDLE, 
sys.DBMS_SQLTUNE_UTIL0.SQLTEXT_TO_SQLID(SQL_TEXT) SQL_TEXT_to_SQL_ID
from dba_sql_plan_baselines;