CREATE TABLE "BOOKER"."ABC"
(
"EMPLOYEE_ID"  VARCHAR(11),
"WAREHOUSE_ID" CHAR(4),
"PERMISSION_MASK" INT NOT NULL
)
SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
NOCOMPRESS LOGGING
STORAGE(INITIAL 524288 NEXT 524288 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "ADMINISTRATOR";

CREATE OR REPLACE PUBLIC synonym ABC for BOOKER.ABC;

ALTER TABLE BOOKER.ABC ADD CONSTRAINT PK_ABC PRIMARY KEY (EMPLOYEE_ID,WAREHOUSE_ID)
USING INDEX TABLESPACE ADMINISTRATOR_IDX
INITRANS 12 STORAGE ( PCTINCREASE 0 FREELISTS 4 )
;
