BEGIN;
    INSERT INTO booker.savepoint VALUES (1, 'savepoint1',common_time.sysdate());
    
    SAVEPOINT my_savepoint1;
    INSERT INTO booker.savepoint VALUES (2, 'savepoint2',common_time.sysdate());
    
    SAVEPOINT my_savepoint2;
    INSERT INTO booker.savepoint VALUES (3, 'savepoint3',common_time.sysdate());
    
    SAVEPOINT my_savepoint3;
    INSERT INTO booker.savepoint VALUES (1, 'savepoint1',common_time.sysdate());
    
    SAVEPOINT my_savepoint4;
    INSERT INTO booker.savepoint VALUES (2, 'savepoint2',common_time.sysdate());
    
    SAVEPOINT my_savepoint5;
    INSERT INTO booker.savepoint VALUES (3, 'savepoint3',common_time.sysdate());
    
    SAVEPOINT my_savepoint6;
    INSERT INTO booker.savepoint VALUES (1, 'savepoint1',common_time.sysdate());
    
    SAVEPOINT my_savepoint7;
    INSERT INTO booker.savepoint VALUES (2, 'savepoint2',common_time.sysdate());
    
    SAVEPOINT my_savepoint8;
    INSERT INTO booker.savepoint VALUES (3, 'savepoint3',common_time.sysdate());
    
    SAVEPOINT my_savepoint9;
    INSERT INTO booker.savepoint VALUES (1, 'savepoint1',common_time.sysdate());
    
    SAVEPOINT my_savepoint10;
    INSERT INTO booker.savepoint VALUES (2, 'savepoint2',common_time.sysdate());
    
    SAVEPOINT my_savepoint11;
    INSERT INTO booker.savepoint VALUES (3, 'savepoint3',common_time.sysdate());
    
    SAVEPOINT my_savepoint12;
    INSERT INTO booker.savepoint VALUES (1, 'savepoint1',common_time.sysdate());
    
    SAVEPOINT my_savepoint13;
    INSERT INTO booker.savepoint VALUES (2, 'savepoint2',common_time.sysdate());
    
    SAVEPOINT my_savepoint14;
    INSERT INTO booker.savepoint VALUES (3, 'savepoint3',common_time.sysdate());
    
    SAVEPOINT my_savepoint15;
    INSERT INTO booker.savepoint VALUES (1, 'savepoint1',common_time.sysdate());
    
    SAVEPOINT my_savepoint16;
    INSERT INTO booker.savepoint VALUES (2, 'savepoint2',common_time.sysdate());
    
    SAVEPOINT my_savepoint17;
    INSERT INTO booker.savepoint VALUES (3, 'savepoint3',common_time.sysdate());
    
    SAVEPOINT my_savepoint18;
    INSERT INTO booker.savepoint VALUES (1, 'savepoint1',common_time.sysdate());
    
    SAVEPOINT my_savepoint19;
    INSERT INTO booker.savepoint VALUES (2, 'savepoint2',common_time.sysdate());
    
    SAVEPOINT my_savepoint20;
    INSERT INTO booker.savepoint VALUES (3, 'savepoint3',common_time.sysdate());
    
    SAVEPOINT my_savepoint21;
    INSERT INTO booker.savepoint VALUES (1, 'savepoint1',common_time.sysdate());
    
    SAVEPOINT my_savepoint22;
    INSERT INTO booker.savepoint VALUES (2, 'savepoint2',common_time.sysdate());
    
    SAVEPOINT my_savepoint23;
    INSERT INTO booker.savepoint VALUES (3, 'savepoint3',common_time.sysdate());
    
    SAVEPOINT my_savepoint24;
    INSERT INTO booker.savepoint VALUES (1, 'savepoint1',common_time.sysdate());
    
    SAVEPOINT my_savepoint25;
    INSERT INTO booker.savepoint VALUES (2, 'savepoint2',common_time.sysdate());
    
    SAVEPOINT my_savepoint26;
    INSERT INTO booker.savepoint VALUES (3, 'savepoint3',common_time.sysdate());
    
    SAVEPOINT my_savepoint27;
    INSERT INTO booker.savepoint VALUES (1, 'savepoint1',common_time.sysdate());
    
    SAVEPOINT my_savepoint28;
    INSERT INTO booker.savepoint VALUES (2, 'savepoint2',common_time.sysdate());
    
    SAVEPOINT my_savepoint29;
    INSERT INTO booker.savepoint VALUES (3, 'savepoint3',common_time.sysdate());
    
    SAVEPOINT my_savepoint30;
    INSERT INTO booker.savepoint VALUES (1, 'savepoint1',common_time.sysdate());
    
    SAVEPOINT my_savepoint31;
    INSERT INTO booker.savepoint VALUES (2, 'savepoint2',common_time.sysdate());
    
    SAVEPOINT my_savepoint32;
    INSERT INTO booker.savepoint VALUES (3, 'savepoint3',common_time.sysdate());
    
    SAVEPOINT my_savepoint33;
    INSERT INTO booker.savepoint VALUES (1, 'savepoint1',common_time.sysdate());
    
    SAVEPOINT my_savepoint34;
    INSERT INTO booker.savepoint VALUES (2, 'savepoint2',common_time.sysdate());
    
    SAVEPOINT my_savepoint35;
    INSERT INTO booker.savepoint VALUES (3, 'savepoint3',common_time.sysdate());
    
    SAVEPOINT my_savepoint36;
    INSERT INTO booker.savepoint VALUES (1, 'savepoint1',common_time.sysdate());
    
    SAVEPOINT my_savepoint37;
    INSERT INTO booker.savepoint VALUES (2, 'savepoint2',common_time.sysdate());
    
    SAVEPOINT my_savepoint38;
    INSERT INTO booker.savepoint VALUES (3, 'savepoint3',common_time.sysdate());
    
    SAVEPOINT my_savepoint39;
    INSERT INTO booker.savepoint VALUES (1, 'savepoint1',common_time.sysdate());
    
    SAVEPOINT my_savepoint40;
    INSERT INTO booker.savepoint VALUES (2, 'savepoint2',common_time.sysdate());
    
    SAVEPOINT my_savepoint41;
    INSERT INTO booker.savepoint VALUES (3, 'savepoint3',common_time.sysdate());
    
    SAVEPOINT my_savepoint42;
    INSERT INTO booker.savepoint VALUES (1, 'savepoint1',common_time.sysdate());
    
    SAVEPOINT my_savepoint43;
    INSERT INTO booker.savepoint VALUES (2, 'savepoint2',common_time.sysdate());
    
    SAVEPOINT my_savepoint44;
    INSERT INTO booker.savepoint VALUES (3, 'savepoint3',common_time.sysdate());
    
    SAVEPOINT my_savepoint45;
    INSERT INTO booker.savepoint VALUES (1, 'savepoint1',common_time.sysdate());
    
    SAVEPOINT my_savepoint46;
    INSERT INTO booker.savepoint VALUES (2, 'savepoint2',common_time.sysdate());
    
    SAVEPOINT my_savepoint47;
    INSERT INTO booker.savepoint VALUES (3, 'savepoint3',common_time.sysdate());
    
    SAVEPOINT my_savepoint48;
    INSERT INTO booker.savepoint VALUES (1, 'savepoint1',common_time.sysdate());
    
    SAVEPOINT my_savepoint49;
    INSERT INTO booker.savepoint VALUES (2, 'savepoint2',common_time.sysdate());
    
    SAVEPOINT my_savepoint50;
    INSERT INTO booker.savepoint VALUES (3, 'savepoint3',common_time.sysdate());
    
    SAVEPOINT my_savepoint51;
    INSERT INTO booker.savepoint VALUES (1, 'savepoint1',common_time.sysdate());
    
    SAVEPOINT my_savepoint52;
    INSERT INTO booker.savepoint VALUES (2, 'savepoint2',common_time.sysdate());
    
    SAVEPOINT my_savepoint53;
    INSERT INTO booker.savepoint VALUES (3, 'savepoint3',common_time.sysdate());
    
    SAVEPOINT my_savepoint54;
    INSERT INTO booker.savepoint VALUES (1, 'savepoint1',common_time.sysdate());
    
    SAVEPOINT my_savepoint55;
    INSERT INTO booker.savepoint VALUES (2, 'savepoint2',common_time.sysdate());
    
    SAVEPOINT my_savepoint56;
    INSERT INTO booker.savepoint VALUES (3, 'savepoint3',common_time.sysdate());
    
    SAVEPOINT my_savepoint57;
    INSERT INTO booker.savepoint VALUES (1, 'savepoint1',common_time.sysdate());
    
    SAVEPOINT my_savepoint58;
    INSERT INTO booker.savepoint VALUES (2, 'savepoint2',common_time.sysdate());
    
    SAVEPOINT my_savepoint59;
    INSERT INTO booker.savepoint VALUES (3, 'savepoint3',common_time.sysdate());
    
    SAVEPOINT my_savepoint60;
    INSERT INTO booker.savepoint VALUES (1, 'savepoint1',common_time.sysdate());
    
    SAVEPOINT my_savepoint61;
    INSERT INTO booker.savepoint VALUES (2, 'savepoint2',common_time.sysdate());
    
    SAVEPOINT my_savepoint62;
    INSERT INTO booker.savepoint VALUES (3, 'savepoint3',common_time.sysdate());
    
    SAVEPOINT my_savepoint63;
    INSERT INTO booker.savepoint VALUES (1, 'savepoint1',common_time.sysdate());
    
    SAVEPOINT my_savepoint64;
    INSERT INTO booker.savepoint VALUES (1, 'savepoint1',common_time.sysdate());
    
    SAVEPOINT my_savepoint65;
    INSERT INTO booker.savepoint VALUES (2, 'savepoint2',common_time.sysdate());
    
    SAVEPOINT my_savepoint66;
    INSERT INTO booker.savepoint VALUES (3, 'savepoint3',common_time.sysdate());
    
    SAVEPOINT my_savepoint67;
    INSERT INTO booker.savepoint VALUES (1, 'savepoint1',common_time.sysdate());
    
    SAVEPOINT my_savepoint68;
    INSERT INTO booker.savepoint VALUES (2, 'savepoint2',common_time.sysdate());
    
    SAVEPOINT my_savepoint69;
    INSERT INTO booker.savepoint VALUES (3, 'savepoint3',common_time.sysdate());
    
    SAVEPOINT my_savepoint70;
    INSERT INTO booker.savepoint VALUES (1, 'savepoint1',common_time.sysdate());
    
    SAVEPOINT my_savepoint71;
    INSERT INTO booker.savepoint VALUES (2, 'savepoint2',common_time.sysdate());
    
    SAVEPOINT my_savepoint72;
    INSERT INTO booker.savepoint VALUES (3, 'savepoint3',common_time.sysdate());
    
    SAVEPOINT my_savepoint73;
    INSERT INTO booker.savepoint VALUES (1, 'savepoint1',common_time.sysdate());
    
    SAVEPOINT my_savepoint74;
    INSERT INTO booker.savepoint VALUES (2, 'savepoint2',common_time.sysdate());
    
    SAVEPOINT my_savepoint75;
    INSERT INTO booker.savepoint VALUES (3, 'savepoint3',common_time.sysdate());
    
    SAVEPOINT my_savepoint76;
    INSERT INTO booker.savepoint VALUES (1, 'savepoint1',common_time.sysdate());
    
    SAVEPOINT my_savepoint77;
    INSERT INTO booker.savepoint VALUES (2, 'savepoint2',common_time.sysdate());
    
    SAVEPOINT my_savepoint78;
    INSERT INTO booker.savepoint VALUES (3, 'savepoint3',common_time.sysdate());
    
    SAVEPOINT my_savepoint79;
    INSERT INTO booker.savepoint VALUES (1, 'savepoint1',common_time.sysdate());
    
    SAVEPOINT my_savepoint80;
    INSERT INTO booker.savepoint VALUES (2, 'savepoint2',common_time.sysdate());
    
    SAVEPOINT my_savepoint81;
    INSERT INTO booker.savepoint VALUES (3, 'savepoint3',common_time.sysdate());
    
    SAVEPOINT my_savepoint82;
    INSERT INTO booker.savepoint VALUES (1, 'savepoint1',common_time.sysdate());
    
    SAVEPOINT my_savepoint83;
    INSERT INTO booker.savepoint VALUES (2, 'savepoint2',common_time.sysdate());
    
    SAVEPOINT my_savepoint84;
    INSERT INTO booker.savepoint VALUES (3, 'savepoint3',common_time.sysdate());
    
    SAVEPOINT my_savepoint85;
    INSERT INTO booker.savepoint VALUES (1, 'savepoint1',common_time.sysdate());
    
    SAVEPOINT my_savepoint86;
    INSERT INTO booker.savepoint VALUES (2, 'savepoint2',common_time.sysdate());
    
    SAVEPOINT my_savepoint87;
    INSERT INTO booker.savepoint VALUES (3, 'savepoint3',common_time.sysdate());
    
    SAVEPOINT my_savepoint88;
    INSERT INTO booker.savepoint VALUES (1, 'savepoint1',common_time.sysdate());
    
    SAVEPOINT my_savepoint89;
    INSERT INTO booker.savepoint VALUES (2, 'savepoint2',common_time.sysdate());
    
    SAVEPOINT my_savepoint90;
    INSERT INTO booker.savepoint VALUES (3, 'savepoint3',common_time.sysdate());
    
    SAVEPOINT my_savepoint91;
    INSERT INTO booker.savepoint VALUES (1, 'savepoint1',common_time.sysdate());
    
    SAVEPOINT my_savepoint92;
    INSERT INTO booker.savepoint VALUES (2, 'savepoint2',common_time.sysdate());
    
    SAVEPOINT my_savepoint93;
    INSERT INTO booker.savepoint VALUES (3, 'savepoint3',common_time.sysdate());
    
    SAVEPOINT my_savepoint94;
    INSERT INTO booker.savepoint VALUES (1, 'savepoint1',common_time.sysdate());
    
    SAVEPOINT my_savepoint95;
    INSERT INTO booker.savepoint VALUES (2, 'savepoint2',common_time.sysdate());
    
    SAVEPOINT my_savepoint96;
    INSERT INTO booker.savepoint VALUES (3, 'savepoint3',common_time.sysdate());
    
    SAVEPOINT my_savepoint97;
    INSERT INTO booker.savepoint VALUES (1, 'savepoint1',common_time.sysdate());
    
    SAVEPOINT my_savepoint98;
    INSERT INTO booker.savepoint VALUES (2, 'savepoint2',common_time.sysdate());
    
    SAVEPOINT my_savepoint99;
    INSERT INTO booker.savepoint VALUES (3, 'savepoint3',common_time.sysdate());
    
    SAVEPOINT my_savepoint100;
    INSERT INTO booker.savepoint VALUES (1, 'savepoint1',common_time.sysdate());
    
    SAVEPOINT my_savepoint101;
    INSERT INTO booker.savepoint VALUES (2, 'savepoint2',common_time.sysdate());
    
    SAVEPOINT my_savepoint102;
    INSERT INTO booker.savepoint VALUES (3, 'savepoint3',common_time.sysdate());
    
    SAVEPOINT my_savepoint103;
    INSERT INTO booker.savepoint VALUES (1, 'savepoint1',common_time.sysdate());
    
    SAVEPOINT my_savepoint104;
    INSERT INTO booker.savepoint VALUES (2, 'savepoint2',common_time.sysdate());
    
    SAVEPOINT my_savepoint105;
    INSERT INTO booker.savepoint VALUES (3, 'savepoint3',common_time.sysdate());
    
    SAVEPOINT my_savepoint106;
    INSERT INTO booker.savepoint VALUES (1, 'savepoint1',common_time.sysdate());
    
    SAVEPOINT my_savepoint107;
    INSERT INTO booker.savepoint VALUES (2, 'savepoint2',common_time.sysdate());
    
    SAVEPOINT my_savepoint108;
    INSERT INTO booker.savepoint VALUES (3, 'savepoint3',common_time.sysdate());
    
    SAVEPOINT my_savepoint109;
    INSERT INTO booker.savepoint VALUES (1, 'savepoint1',common_time.sysdate());
    
    SAVEPOINT my_savepoint110;
    INSERT INTO booker.savepoint VALUES (2, 'savepoint2',common_time.sysdate());
    
    SAVEPOINT my_savepoint111;
    INSERT INTO booker.savepoint VALUES (3, 'savepoint3',common_time.sysdate());
    
    SAVEPOINT my_savepoint112;
    INSERT INTO booker.savepoint VALUES (1, 'savepoint1',common_time.sysdate());
    
    SAVEPOINT my_savepoint113;
    INSERT INTO booker.savepoint VALUES (2, 'savepoint2',common_time.sysdate());
    
    SAVEPOINT my_savepoint114;
    INSERT INTO booker.savepoint VALUES (3, 'savepoint3',common_time.sysdate());
    
    SAVEPOINT my_savepoint115;
    INSERT INTO booker.savepoint VALUES (1, 'savepoint1',common_time.sysdate());
    
    SAVEPOINT my_savepoint116;
    INSERT INTO booker.savepoint VALUES (2, 'savepoint2',common_time.sysdate());
    
    SAVEPOINT my_savepoint117;
    INSERT INTO booker.savepoint VALUES (3, 'savepoint3',common_time.sysdate());
    
    SAVEPOINT my_savepoint118;
    INSERT INTO booker.savepoint VALUES (1, 'savepoint1',common_time.sysdate());
    
    SAVEPOINT my_savepoint119;
    INSERT INTO booker.savepoint VALUES (2, 'savepoint2',common_time.sysdate());
    
    SAVEPOINT my_savepoint120;
    INSERT INTO booker.savepoint VALUES (3, 'savepoint3',common_time.sysdate());
    
    SAVEPOINT my_savepoint121;
    INSERT INTO booker.savepoint VALUES (1, 'savepoint1',common_time.sysdate());
    
    SAVEPOINT my_savepoint122;
    INSERT INTO booker.savepoint VALUES (2, 'savepoint2',common_time.sysdate());
    
    SAVEPOINT my_savepoint123;
    INSERT INTO booker.savepoint VALUES (3, 'savepoint3',common_time.sysdate());
    
    SAVEPOINT my_savepoint124;
    INSERT INTO booker.savepoint VALUES (1, 'savepoint1',common_time.sysdate());
    
    SAVEPOINT my_savepoint125;
    INSERT INTO booker.savepoint VALUES (2, 'savepoint2',common_time.sysdate());
    
    SAVEPOINT my_savepoint126;
    INSERT INTO booker.savepoint VALUES (3, 'savepoint3',common_time.sysdate());
    
    SAVEPOINT my_savepoint127;
    INSERT INTO booker.savepoint VALUES (1, 'savepoint1',common_time.sysdate());
    
    SAVEPOINT my_savepoint128;

--END;
